# Generated by Django 6.0.1 on 2026-01-31 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CueDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cue_id', models.CharField(max_length=20, unique=True)),
                ('design_style', models.CharField(choices=[('traditional_classic', 'Traditional Classic'), ('modern_minimal', 'Modern Minimal'), ('ornate', 'Ornate'), ('art_deco', 'Art Deco'), ('contemporary', 'Contemporary')], max_length=30)),
                ('overall_length_in', models.FloatField()),
                ('symmetry_type', models.CharField(choices=[('radial', 'Radial'), ('bilateral', 'Bilateral'), ('asymmetric', 'Asymmetric')], max_length=15)),
                ('era_influence', models.CharField(choices=[('vintage', 'Vintage'), ('traditional', 'Traditional'), ('modern', 'Modern'), ('contemporary', 'Contemporary')], max_length=20)),
                ('complexity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['cue_id'],
            },
        ),
        migrations.CreateModel(
            name='CueSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=50)),
                ('section_type', models.CharField(choices=[('forearm', 'Forearm'), ('handle', 'Handle'), ('butt_sleeve', 'Butt Sleeve')], max_length=15)),
                ('start_position_in', models.FloatField()),
                ('end_position_in', models.FloatField()),
                ('outer_diameter_start_mm', models.FloatField()),
                ('outer_diameter_end_mm', models.FloatField()),
                ('inlay_patterns', models.JSONField(blank=True, default=list)),
                ('cue_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cues.cuedesign')),
            ],
            options={
                'ordering': ['start_position_in'],
                'unique_together': {('cue_design', 'section_id')},
            },
        ),
    ]
