# Generated by Django 6.0.1 on 2026-01-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuedesign',
            name='shaft_diameter_mm',
            field=models.FloatField(blank=True, help_text='Shaft diameter at joint', null=True),
        ),
        migrations.AddField(
            model_name='cuedesign',
            name='shaft_length_in',
            field=models.FloatField(blank=True, help_text='Total shaft length', null=True),
        ),
        migrations.AddField(
            model_name='cuedesign',
            name='tip_size_mm',
            field=models.FloatField(blank=True, help_text='Tip diameter in mm', null=True),
        ),
        migrations.AddField(
            model_name='cuedesign',
            name='tip_type',
            field=models.CharField(blank=True, choices=[('leather', 'Leather'), ('phenolic', 'Phenolic'), ('layered', 'Layered')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cuesection',
            name='balance_point_in',
            field=models.FloatField(blank=True, help_text='Distance from joint end to balance point', null=True),
        ),
        migrations.AddField(
            model_name='cuesection',
            name='finish_type',
            field=models.CharField(blank=True, choices=[('oil', 'Oil Finish'), ('polyurethane', 'Polyurethane'), ('lacquer', 'Lacquer'), ('wax', 'Wax')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cuesection',
            name='joint_collar_diameter_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuesection',
            name='joint_pin_material',
            field=models.CharField(blank=True, choices=[('stainless_steel', 'Stainless Steel'), ('brass', 'Brass'), ('titanium', 'Titanium')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cuesection',
            name='joint_type',
            field=models.CharField(blank=True, choices=[('5_16_18', '5/16-18'), ('3_8_10', '3/8-10'), ('5_16_14', '5/16-14'), ('radial', 'Radial Pin'), ('uni_loc', 'Uni-Loc'), ('quick_release', 'Quick Release')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cuesection',
            name='production_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cuesection',
            name='qc_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_production', 'In Production'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='cuesection',
            name='stain_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cuesection',
            name='weight_oz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuesection',
            name='wood_species',
            field=models.CharField(blank=True, choices=[('maple', 'Maple'), ('ebony', 'Ebony'), ('rosewood', 'Rosewood'), ('cocobolo', 'Cocobolo'), ('bubinga', 'Bubinga'), ('purpleheart', 'Purpleheart')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cuesection',
            name='wrap_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cuesection',
            name='wrap_pattern',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cuesection',
            name='wrap_type',
            field=models.CharField(blank=True, choices=[('irish_linen', 'Irish Linen'), ('leather', 'Leather'), ('synthetic', 'Synthetic'), ('none', 'None')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cuesection',
            name='section_type',
            field=models.CharField(choices=[('joint', 'Joint'), ('forearm', 'Forearm'), ('handle', 'Handle'), ('sleeve', 'Sleeve'), ('butt', 'Butt')], max_length=15),
        ),
    ]
